package com.bizgenai.guardrail;

import com.bizgenai.entity.Blueprint;
import com.bizgenai.entity.Category;
import com.bizgenai.guardrail.rules.GuardrailRule;
import com.bizgenai.guardrail.rules.RuleResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class GuardrailEngine {

    private static final Logger log = LoggerFactory.getLogger(GuardrailEngine.class);
    private final List<GuardrailRule> rules;

    public GuardrailEngine(List<GuardrailRule> rules) {
        this.rules = rules.stream()
                .sorted(Comparator.comparingInt(GuardrailRule::getOrder))
                .collect(Collectors.toList());
        log.info("GuardrailEngine initialized with {} rules", rules.size());
    }

    public GuardrailResult apply(List<String> variations, Blueprint blueprint, Category category) {
        List<String> processedVariations = new ArrayList<>();
        List<GuardrailResult.Warning> allWarnings = new ArrayList<>();
        List<GuardrailResult.Placeholder> allPlaceholders = new ArrayList<>();

        for (String variation : variations) {
            String processed = variation;

            for (GuardrailRule rule : rules) {
                if (rule.appliesTo(category, blueprint)) {
                    log.debug("Applying rule: {} to variation", rule.getClass().getSimpleName());
                    RuleResult result = rule.apply(processed, blueprint);
                    processed = result.getModifiedContent();
                    allWarnings.addAll(result.getWarnings());
                    allPlaceholders.addAll(result.getPlaceholders());
                }
            }

            processedVariations.add(processed);
        }

        // Collect disclaimers from blueprint
        List<String> disclaimers = new ArrayList<>();
        if (blueprint.getRequiredDisclaimers() != null) {
            for (String disclaimerKey : blueprint.getRequiredDisclaimers()) {
                disclaimers.add(getDisclaimerText(disclaimerKey));
            }
        }

        // Add category-level disclaimer if required
        if (category != null && Boolean.TRUE.equals(category.getRequiresDisclaimer())) {
            disclaimers.add(getCategoryDisclaimer(category));
        }

        // Remove duplicate warnings
        List<GuardrailResult.Warning> uniqueWarnings = allWarnings.stream()
                .distinct()
                .collect(Collectors.toList());

        return GuardrailResult.builder()
                .processedVariations(processedVariations)
                .disclaimers(disclaimers)
                .warnings(uniqueWarnings)
                .detectedPlaceholders(allPlaceholders)
                .build();
    }

    private String getDisclaimerText(String disclaimerKey) {
        return switch (disclaimerKey) {
            case "DRAFT_ONLY" -> "This document is a DRAFT only and has been generated by an AI system. It is not a final legal document.";
            case "LEGAL_REVIEW_REQUIRED" -> "This draft must be reviewed by a qualified legal professional before use. Laws vary by jurisdiction and business type.";
            case "NOT_LEGAL_ADVICE" -> "This content does not constitute legal advice. BizGen AI and its creators are not responsible for any legal issues arising from the use of this draft.";
            default -> "Please review this content before use.";
        };
    }

    private String getCategoryDisclaimer(Category category) {
        if ("legal".equalsIgnoreCase(category.getName())) {
            return "All legal documents generated are drafts and require professional legal review before use.";
        }
        return "This content was generated by AI and should be reviewed before publication.";
    }
}
