import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card } from '@/components/common/Card';
import { Badge } from '@/components/common/Badge';
import { Button } from '@/components/common/Button';
import { PageLoader } from '@/components/common/Loader';
import { EmptyState } from '@/components/common/EmptyState';
import { fetchCategoryById, fetchTemplates, Category, Template } from '@/api';
import { DIFFICULTY_COLORS, DIFFICULTY_LABELS } from '@/utils/constants';
import { ArrowLeft, Clock, Star, ChevronRight, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';

export function TemplateSelection() {
  const { categoryId } = useParams<{ categoryId: string }>();
  const navigate = useNavigate();
  const [category, setCategory] = useState<Category | null>(null);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (categoryId) {
      loadData();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [categoryId]);

  const loadData = async () => {
    if (!categoryId) return;
    
    setLoading(true);
    try {
      const [categoryData, templatesData] = await Promise.all([
        fetchCategoryById(categoryId),
        fetchTemplates(categoryId),
      ]);
      setCategory(categoryData);
      setTemplates(templatesData);
    } catch (error) {
      console.error('Failed to load templates:', error);
      toast.error('Failed to load templates. Please try again.');
      navigate('/create');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <PageLoader text="Loading templates..." />;
  }

  if (!category) {
    return (
      <EmptyState
        icon="folder"
        title="Category not found"
        description="The category you're looking for doesn't exist."
        actionLabel="Go back"
        onAction={() => navigate('/create')}
      />
    );
  }

  return (
    <div className="space-y-6">
      {/* Back Button & Header */}
      <div>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate('/create')}
          leftIcon={<ArrowLeft className="h-4 w-4" />}
          className="mb-4"
        >
          Back to categories
        </Button>

        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 mb-2">
              {category.displayName}
            </h1>
            <p className="text-slate-500 max-w-2xl">
              {category.description}
            </p>
          </div>
          <Badge variant="outline">
            {templates.length} template{templates.length !== 1 ? 's' : ''}
          </Badge>
        </div>
      </div>

      {/* Legal Disclaimer Banner */}
      {category.requiresDisclaimer && (
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="font-medium text-amber-800">Draft Documents Only</h4>
            <p className="text-sm text-amber-700">
              These are draft documents generated by AI. They must be reviewed by a qualified legal professional before use.
            </p>
          </div>
        </div>
      )}

      {/* Templates Grid */}
      {templates.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {templates.map((template) => {
            const difficultyColor = DIFFICULTY_COLORS[template.difficulty] || DIFFICULTY_COLORS.EASY;
            const difficultyLabel = DIFFICULTY_LABELS[template.difficulty] || 'Easy';

            return (
              <Card
                key={template.id}
                variant="interactive"
                className="cursor-pointer group flex flex-col"
                onClick={() => navigate(`/app/create/${categoryId}/${template.id}`)}
              >
                <div className="flex-1">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-2">
                      {template.popular && (
                        <Badge variant="warning" size="sm">
                          <Star className="h-3 w-3 mr-1" />
                          Popular
                        </Badge>
                      )}
                    </div>
                    <Badge className={difficultyColor} size="sm">
                      {difficultyLabel}
                    </Badge>
                  </div>

                  <h3 className="text-lg font-semibold text-slate-900 mb-2 group-hover:text-blue-600 transition-colors">
                    {template.name}
                  </h3>

                  <p className="text-sm text-slate-500 line-clamp-2 mb-4">
                    {template.description}
                  </p>
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-slate-100">
                  <div className="flex items-center gap-1.5 text-slate-400">
                    <Clock className="h-4 w-4" />
                    <span className="text-sm">{template.estimatedTime}</span>
                  </div>
                  <div className="flex items-center gap-1 text-blue-600 text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity">
                    Start
                    <ChevronRight className="h-4 w-4" />
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      ) : (
        <EmptyState
          icon="file"
          title="No templates available"
          description="There are no templates available in this category yet."
          actionLabel="Go back"
          onAction={() => navigate('/create')}
        />
      )}
    </div>
  );
}
