package com.bizgenai.guardrail.rules;

import com.bizgenai.entity.Blueprint;
import com.bizgenai.entity.Category;
import com.bizgenai.guardrail.GuardrailResult;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class DisclaimerRule implements GuardrailRule {

    private static final String LEGAL_HEADER = "\n⚠️ DRAFT DOCUMENT - FOR REVIEW ONLY ⚠️\n" +
            "This document has been generated by an AI system and is a DRAFT only.\n" +
            "It must be reviewed by a qualified legal professional before use.\n\n";

    private static final String LEGAL_FOOTER = "\n\n---\n" +
            "DISCLAIMER: This document was generated as a draft and requires review by a qualified legal professional before use. " +
            "This content does not constitute legal advice. Laws vary by jurisdiction and business type.\n";

    @Override
    public boolean appliesTo(Category category, Blueprint blueprint) {
        return category != null && "legal".equalsIgnoreCase(category.getName());
    }

    @Override
    public RuleResult apply(String content, Blueprint blueprint) {
        List<GuardrailResult.Warning> warnings = new ArrayList<>();

        // Add header and footer disclaimers for legal documents
        String modifiedContent = LEGAL_HEADER + content + LEGAL_FOOTER;

        warnings.add(GuardrailResult.Warning.builder()
                .type(GuardrailResult.WarningType.LEGAL_NOTICE)
                .message("This is a draft document that requires legal review before use")
                .severity(GuardrailResult.Severity.CRITICAL)
                .build());

        return RuleResult.builder()
                .modifiedContent(modifiedContent)
                .warnings(warnings)
                .build();
    }

    @Override
    public int getOrder() {
        return 10; // Run last to add disclaimers after other processing
    }
}
